<?php
function cart_doc_generator() { echo 'hello world'; }
/*
function cart_doc_generator() {
    ?>

    <div class="ccms_form_element cfdiv_custom" id="style_container_div">
    <label>Shopping Cart</label><select size="1" id="shoppingCart" class=" validate['required']" title="" type="select" name="style">
        <option value="">--- Choose A Cart ---</option>
        <option value="Magento">Magento</option>
        <option value="Shopify">Shopify</option>
        <option value="Big Commerce">Big Commerce</option>
    </select><div class="clear"></div><div id="error-message-style"></div></div>
    <div id="Magento"  class="style-sub-1"  style="display: none;" name="stylesub1" onchange="ChangeDropdowns(this.value)">
        <label>Version Number</label>
        <select>
            <option value="">-Choose An Ale-</option>
            <option value="1.0">1.0</option>
            <option value="1.1">1.1</option>
            <option value="1.2.4">1.2.4</option>
            <option value="1.6.1">1.6.1</option>
            <option value="1.7.1">1.7.1</option>
        </select>
    </div>
    <div id="Shopify"  class="style-sub-1"  style="display: none;" name="stylesub1" onchange="ChangeDropdowns(this.value)">
        <label>Which Kind of Lager?</label>
        <select>
            <option value="">-Choose A Lager-</option>
            <option value="American Lager">American Lager</option>
            <option value="Czech Lager">Czech Lager</option>
            <option value="European Lager">European Lager</option>
            <option value="German Lager">German Lager</option>
            <option value="Japanese Lager">Japanese Lager</option>
        </select>
    </div>
    <div id="Big Commerce"  class="style-sub-1"  style="display: none;" name="stylesub1" onchange="ChangeDropdowns(this.value)">
        <label>Which Kind of Hybrid?</label>
        <select>
            <option value="">-Choose A Hybrid-</option>
            <option value="Fruit / Vegetable Beer">Fruit / Vegetable Beer</option>
            <option value="Herbed / Spiced Beer">Herbed / Spiced Beer</option>
            <option value="Smoked Beer">Smoked Beer</option>
        </select>
    </div><div class="clear"></div><div id="error-message-style-sub-1"></div></div>


    <script>
        $("#shoppingCart").change ( function () {
            var targID  = $(this).val ();
            $("div.style-sub-1").hide ();
            $('#' + targID).show ();
        } )
    </script>
    <?
}
*/